name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release Note
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate changelog with Commitizen
        uses: commitizen-tools/commitizen-action@0.21.0
        with:
          changelog_increment_filename: changelog.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: changelog.md